server {
    server_name dadanggeun.skrr.store;
    client_max_body_size 50M;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        root /var/www/dadanggeun/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /uploads/ {
        alias /var/www/dadanggeun/backend/uploads/;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/dadanggeun.skrr.store/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dadanggeun.skrr.store/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = dadanggeun.skrr.store) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name dadanggeun.skrr.store;
    return 404;
}
